---
- hosts: SERVERBDD
  become: yes
  tasks:
  - name: Use /usr/bin/python3 as default interpreter
    set_fact:
      ansible_python_interpreter: /usr/bin/python3

  - name: Install MariaDB
    yum:
      name: mariadb-server
      state: latest
      update_cache: yes

  - name: Enable MariaDB service
    service:
      name: mariadb
      state: started
      enabled: yes

  - name: Install python3 and PyMySQL
    yum:
      name:
        - python3
        - python3-pip
      state: present

  - name: Set root password
    community.mysql.mysql_user:
      login_user: root
      login_password: ''
      user: root
      password: T001k1t_2022
      priv: '*.*:ALL,GRANT'
      host_all: yes

  - name: Create Database
    mysql_db:
      name: SNOW
      login_user: root
      login_password: T001k1t_2022
      state: present

  - name: Create mysql User defined database
    mysql_user:
      name: snowuser
      password: snowuser
      priv: '*.*:ALL,GRANT'
      login_user: root
      login_password: T001k1t_2022
      state: present
    when:
      - create_database
      - database is defined
      - create_db_user
      - db_user_name is defined