---
- hosts: SERVERBDD
  become: yes
  tasks:
  - name: Use /usr/bin/python3 as default interpreter
    set_fact:
      ansible_python_interpreter: /usr/bin/python3

  - name: Install MariaDB
    yum:
      name: mariadb-server
      state: latest
      update_cache: yes

  - name: Enable MariaDB service
    service:
      name: mariadb
      state: started
      enabled: yes

  - name: Install python3 and PyMySQL
    yum:
      name:
        - python3
        - python3-pip
      state: present

  - name: Create Database
    mysql_db:
      name: SNOW
      login_user: root
      login_password: T001k1t_2022
      state: present

  - name: Create mysql User defined database
    mysql_user:
      name: snowuser
      password: snowuser
      priv: 'SNOW.*:ALL,GRANT'
      login_user: root
      login_password: T001k1t_2022
      state: present

  - name: Install python3-firewall
    yum:
      name: python3-firewall
      state: present
      
  - name: Install firewalld
    yum:
      name: firewalld
      state: latest

  - name: Start firewalld
    service:
      name: firewalld
      state: started
      enabled: yes

  - name: Open MariaDB port in firewall
    firewalld:
      port: 3306/tcp
      permanent: yes
      state: enabled
      immediate: yes