---
- hosts: SERVERBDD
  become: yes
  tasks:
    - name: Install required firewall service
      yum:
        name: firewalld
        state: latest

    - name: Start firewalld service
      service:
        name: firewalld
        state: started
        enabled: yes

    - name: Open MariaDB port in firewall
      firewalld:
        port: 3306/tcp
        permanent: true
        state: enabled
        immediate: yes
