---
- hosts: SERVERBDD
  become: yes
  tasks:
    - name: Set root password
        community.mysql.mysql_user:
          login_user: root
          login_password:
          user: root
          password:
          priv: "*.*:ALL,GRANT"
          host_all: yes
