---
- name: Arrêt de l'Instance Cible
  hosts: target_server
  become: true
  tasks:
    - name: Arrêter l'instance ServiceNow cible
      command: /glide/nodes/{{ target_instance_port }}/shutdown.sh
